### PR TITLE
Camel-AWS S3 example: Use a Transformation instead of a converter

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by omarsmak** [comment]
Converter is not more suitable here? Since we need to convert the data to `byte[]` before sending it to Kafka, same goes for the other side. Unless you have different purpose here though

**Comment by oscerd** [comment]
This was just for showing how can you create a transformation. What I can do is leaving the converter and add the transformation for completeness

**Comment by omarsmak** [comment]
Yeah makes sense, also I am working on this ticket https://github.com/apache/camel-kafka-connector/issues/16 that complement the transformation

**Comment by orpiske** [comment]
@oscerd I think it's very useful to leave this. I've playing with a ElasticSearch test and @valdar suggested a transformer might be do the trick.

**Comment by oscerd** [comment]
So, I re-added the converter and as default we'll use that in the example, but I committed the transformation example and leave the configuration commented in the source properties file.

**Pull request merged**
