### PR TITLE
Minor cleanups throughout the code base

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
For a moment I thought it was GH crushing my dreams of an easy PR, but it looks like it's related to a missing 3.8.0-SNAPSHOT dependency. I'll check soon.

**Comment by oscerd** [comment]
we need to switch to 0.9.0-SNAPSHOT

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
and camel 3.9.0-SNAPSHOT

**Comment by orpiske** [comment]
> and camel 3.9.0-SNAPSHOT

ACK. I'll do that on a separate PR.

**Pull request merged**
