### PR TITLE
Update try-it-out-locally.adoc

### PR DESCRIPTION
**Pull request by duanasq**
Mention how to build individual connectors only.

As per https://github.com/apache/camel-kafka-connector/issues/1264

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Can you please open the same PR against main branch?

**Comment by oscerd** [comment]
Backported on main too.

**Comment by oscerd** [comment]
Thanks.

**Comment by duanasq** [comment]
oh thank you just sat down to do it but it's done

**Pull request merged**
