### PR TITLE
Point to 3.7.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
@orpiske may I ask you to have a look at aligning the PR here? So we could have the ckc camel-master aligned to 3.7.0-SNAPSHOT and releasing 0.7.0 will be easier. Thanks.

**Comment by orpiske** [comment]
@oscerd absolutely. I will take care of this one.

**Comment by oscerd** [comment]
Awesome, thanks a lot.

**Comment by orpiske** [comment]
This is caused by moving some of the test infra code to Camel Core. I will provide a PR for camel-master adjusting this soon (or, I think you can go ahead and merge this code, and I will make sure to fix it right after you merge).

**Comment by oscerd** [comment]
I need to rebase I guess.

**Comment by oscerd** [comment]
I'm closing this, so you can have a look from the beginning.

**Pull request closed without merging**
