### PR TITLE
Upgrade to Camel 3.18.0

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@oscerd this is still pretty broken. The tests are failing because of this:

```
Caused by: java.lang.IllegalStateException: Unsupported definition: ErrorHandlerBuilderRef[{{errorHandler}}]
	at org.apache.camel.reifier.errorhandler.ErrorHandlerReifier.reifier(ErrorHandlerReifier.java:88) ~[camel-core-reifier-3.18.0.jar:3.18.0]
	at org.apache.camel.impl.DefaultModelReifierFactory.createErrorHandler(DefaultModelReifierFactory.java:65) ~[camel-core-engine-3.18.0.jar:3.18.0]
	at org.apache.camel.reifier.ProcessorReifier.wrapInErrorHandler(ProcessorReifier.java:754) ~[camel-core-reifier-3.18.0.jar:3.18.0]
```

Hey @ffang would you mind a review on the CXF changes, please? Thanks!

**Comment by orpiske** [comment]
ErrorHandler reference issue is fixed now.

**Comment by orpiske** [comment]
This one is ready for review.

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
> LGTM. We should merge and prepare a release.

+1

Let's get this in, so it can run for a few cycles in the CI. I'll merge it. Thanks!

**Comment by orpiske** [comment]
@ffang I'll merge it for now, but please feel free to review the CXF and let me know if you notice anything broken. Thanks!

**Pull request merged**
