### PR TITLE
(backport 0.7.x) Fix issue #159: camel components secret options are showed in logs

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by oscerd — COMMENTED** [review]
I think you need to change camel-dependencies version too, here and on camel-master

**Comment by orpiske** [comment]
> I think you need to change camel-dependencies version too, here and on camel-master

Oh, good point! I also think we need to adjust this: https://github.com/apache/camel-kafka-connector/blob/camel-kafka-connector-0.7.x/pom.xml#L31 

On 0.7.x, it is versioned as 0.8.

**Comment by orpiske** [comment]
BTW, I am going to separate the upgrade change from this/these, otherwise it's going to be messy to figure out what went where. We can leave these ones open and I'll rebase them after the fact.

**Comment by orpiske** [comment]
Ok, this one is done and we should be good to go. Merging and starting the work on fixing the other PR ...

**Pull request merged**
