### PR TITLE
Fix AWS2 Cloud Watch test issues due to LocalStack bug

### PR DESCRIPTION
**Pull request by orpiske**
Dimensions are not working correctly in LocalStack's implementation of cloud watch in LocalStack 0.12.10. This forces the test to use 0.12.9.1

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by valdar — APPROVED** [review]
LGTM

**Comment by orpiske** [comment]
LocalStack issue for reference: https://github.com/localstack/localstack/issues/4026

**Comment by whummer** [comment]
Thanks @orpiske - this should be fixed in LocalStack in the meantime. Can you please give it another try with the `latest` Docker image? (We'll release a new tagged version shortly..). Thanks!

**Comment by orpiske** [comment]
> Thanks @orpiske - this should be fixed in LocalStack in the meantime. Can you please give it another try with the `localstack/localstack:latest` Docker image? (We'll release a new tagged version shortly..). Thanks!

That's great news. I will try a new run tomorrow morning (or, at worst, on Monday) and will report back. Thanks for the quick resolution!

**Pull request merged**
