### PR TITLE
Updated tests after camel 3.9.0 fixed #924.

### LINKED ISSUE #924: Camel-Netty-* connectors are not working
```
[2021-01-27 17:19:21,237] INFO Apache Camel 3.7.0 (camel-1) is shutting down (org.apache.camel.impl.engine.AbstractCamelContext:2907)
[2021-01-27 17:19:21,245] INFO Apache Camel 3.7.0 (camel-1) uptime 78ms (org.apache.camel.impl.engine.AbstractCamelContext:3028)
[2021-01-27 17:19:21,245] INFO Apache Camel 3.7.0 (camel-1) is shutdown in 8ms (org.apache.camel.impl.engine.AbstractCamelContext:3029)
[2021-01-27 17:19:21,246] INFO WorkerSourceTask{id=CamelNettySourceConnector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:416)
[2021-01-27 17:19:21,246] INFO WorkerSourceTask{id=CamelNettySourceConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:433)
[2021-01-27 17:19:21,246] ERROR WorkerSourceTask{id=CamelNettySourceConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Failed to create and start Camel context
	at org.apache.camel.kafkaconnector.CamelSourceTask.start(CamelSourceTask.java:144)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at org.apache.camel.component.netty.SingleTCPNettyServerBootstrapFactory.startServerBootstrap(SingleTCPNettyServerBootstrapFactory.java:184)
	at org.apache.camel.component.netty.SingleTCPNettyServerBootstrapFactory.doStart(SingleTCPNettyServerBootstrapFactory.java:113)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:84)
	at org.apache.camel.component.netty.NettyConsumer.doStart(NettyConsumer.java:75)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3108)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:362)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:282)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:181)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:115)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2889)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2702)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2665)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2431)
	at org.apache.camel.main.SimpleMain.doStart(SimpleMain.java:43)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.kafkaconnector.CamelSourceTask.start(CamelSourceTask.java:141)
	... 8 more
```

with this configuration
```

name=CamelNettySourceConnector
connector.class=org.apache.camel.kafkaconnector.netty.CamelNettySourceConnector
tasks.max=1

# use the kafka converters that better suit your needs, these are just defaults:
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

# comma separated topics to send messages into
topics=mytopic

# mandatory properties (for a complete properties list see the connector documentation):

# The hostname. For the consumer the hostname is localhost or 0.0.0.0. For the producer the hostname is the remote host to connect to
camel.source.path.host=localhost
# The host port number
camel.source.path.port=8182
# The protocol to use which can be tcp or udp. One of: [tcp] [udp]
camel.source.path.protocol=tcp
```

It seems that the BootstrapFactory fails at finding the host. But it's defined.

### PR DESCRIPTION
**Pull request by valdar**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
Thanks @valdar!

**Comment by orpiske** [comment]
@oscerd @valdar on a side note: I think there may be other fixes currently on camel-master that might need to be merged to master. I'm a bit distracted with other activities at the moment and couldn't go through there, but I thought it would be good to highlight this if we start  to see other tests failing.

**Comment by oscerd** [comment]
Yes, but it's important to release. I mean, 3.9.0 is not lts. More or less we should be aligned. I think we'll need to rework the structure, like publishing the documentation only for the latest release and makes the master point to latest camel snapshot. It's completely impossible to maintain in the current way

**Comment by valdar** [comment]
I agree with @oscerd on how we should move forward.

@orpiske wen you have time feel free to backport those commits you are referring to from `camel-master` to `master`. Worst case scenario we could always do a `0.9.1` release...

**Comment by orpiske** [comment]
@oscerd @valdar deal! I'll review these today and will send a PR with them.

**Pull request merged**
