### PR TITLE
Add tests to camel-kafka-connector-generator-maven-plugin

### LINKED ISSUE #166: Add tests to camel-kafka-connector-generator-maven-plugin
Using some maven plugin test project add tests to https://github.com/apache/camel-kafka-connector/tree/master/tooling/camel-kafka-connector-generator-maven-plugin

### PR DESCRIPTION
**Pull request by tadayosi**
Fix #166

Initial attempt at introducing maven it to ckc maven plugin. Running the tests is time consuming, so it's intentionally not integrated with the `integration-test` build cycle by default. You can run them by:
```
mvn clean verify -Pmaven-it
```
at this moment.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Can you please fix this? Error:  /home/runner/work/camel-kafka-connector/camel-kafka-connector/tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources-its/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojoIT/test_generate/pom.xml:1: Line does not match expected header line of '^<\?xml.*>'. [RegexpHeader]
Error:  /home/runner/work/camel-kafka-connector/camel-kafka-connector/tooling/camel-kafka-connector-generator-maven-plugin/src/test/resources/template-connector-package.xml:1: Line does not match expected header line of '^<\?xml.*>'. [RegexpHeader]
Error:  /home/runner/work/camel-kafka-connector/camel-kafka-connector/tooling/camel-kafka-connector-generator-maven-plugin/src/test/java/org/apache/camel/kafkaconnector/maven/GenerateCamelKafkaConnectorsMojoIT.java:45:17: Name 'test_generate' must match pattern '^[a-z][a-zA-Z0-9]*$'. [MethodName]

**Comment by oscerd** [comment]
I think we can also think about creating a gh action testing this stuff during the night or maybe more.

**Comment by tadayosi** [comment]
@oscerd Thanks for your catch-up. I can fix the pom.xml part, but for the method name `test_generate` it's the recommendation by the maven-it-extension plugin because it relies on convention over configuration for resolving the test resource folder `GenerateCamelKafkaConnectorsMojoIT/test_generate` from the class name & method name combo and tries to avoid problems with case-insensitive filesystems. Maybe should I just add some annotation to the method to explicitly ignore the stylecheck?

**Comment by tadayosi** [comment]
@oscerd And great idea for creating a gh action to run the tests nightly. I'll follow up with it after the pull req.

**Comment by oscerd** [comment]
I believe you should add an exclusion at maven checkstyle plugin configuration level

Here:

```
                    <executions>
                        <execution>
                            <id>default-cli</id>
                            <phase>validate</phase>
                            <configuration>
                                <includeResources>false</includeResources>
                                <configLocation>camel-checkstyle.xml</configLocation>
                                <consoleOutput>true</consoleOutput>
                                <failsOnError>${checkstyle.failOnViolation}</failsOnError>
                                <linkXRef>false</linkXRef>
                                <suppressionsLocation>camel-checkstyle-suppressions.xml</suppressionsLocation>
                                <encoding>UTF-8</encoding>
                                <sourceDirectories>
                                    <sourceDirectory>${basedir}/src</sourceDirectory>
                                </sourceDirectories>
                                <headerLocation>header-java.txt</headerLocation>
                                <includes>**/*.java,**/*.groovy,**/*.scala,**/*.xml,**/*.xsd</includes>
                                **<excludes>
                                    **/archetype-resources/**/*.java,**/archetype-resources/**/*.groovy,**/archetype-resources/**/*.scala,**/archetype-resources/**/*.xml,**/org/json/simple/**/*.java,**/camel-checkstyle.xml
                                </excludes>**
                            </configuration>
                            <goals>
                                <goal>checkstyle</goal>
                            </goals>
                        </execution>
                    </executions>
```

**Comment by tadayosi** [comment]
Thanks. Style issues fixed.

**Comment by oscerd** [comment]
Thanks

**Pull request merged**
