### PR TITLE
Fix GH connection timeout issue

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
@oscerd looks like the work-around + cache solved the issue. Wdyt?

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
great stuff, we need to add this to all gh action in camel ecosystem where it is useful

**Comment by oscerd** [comment]
Lets merge this

**Comment by orpiske** [comment]
@oscerd cool, thanks for the review. Let's merge it.

**Pull request merged**
