### PR TITLE
Preparing for 0.8.0 release

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Review by orpiske — APPROVED** [review]
By the commit log, it looks like we have everything. I'm surprised that there is a conflict, though.

**Comment by oscerd** [comment]
Yes, there were a conflict at documentation level. If this is ok, I will close this and push directly.

**Comment by orpiske** [comment]
> Yes, there were a conflict at documentation level. If this is ok, I will close this and push directly.

LGTM

**Comment by oscerd** [comment]
looks good, I'm going to push. Thanks.

**Pull request closed without merging**
