### PR TITLE
Add RecordToJSONTransforms and JSONToRecordTransforms transforms

### PR DESCRIPTION
**Pull request by mathieux51**

### CODE REVIEW

**Review by oscerd — COMMENTED** [review]
Thanks for this. I'll review it soon.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
It seems the build is broken by this PR 

Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default-cli) on project camel-aws2-s3-kafka-connector: An error has occurred in Checkstyle report generation.: Failed during checkstyle configuration: Exception was thrown while processing /home/runner/work/camel-kafka-connector/camel-kafka-connector/connectors/camel-aws2-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2s3/transformers/RecordToJSONTransforms.java: IllegalStateException occurred while parsing file /home/runner/work/camel-kafka-connector/camel-kafka-connector/connectors/camel-aws2-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2s3/transformers/RecordToJSONTransforms.java. /home/runner/work/camel-kafka-connector/camel-kafka-connector/connectors/camel-aws2-s3-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/aws2s3/transformers/RecordToJSONTransforms.java:65:5: expecting SEMI, found 'return' -> [Help 1]

**Comment by mathieux51** [comment]
I will give it a look. @oscerd I'll get you posted.

**Review by oscerd — APPROVED** [review]

**Comment by mathieux51** [comment]
@oscerd Looks like formatting issues. I used the following to format the code:
```bash
function java_fmt {
  java \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -jar ~/.local/bin/google-java-format-1.10.0-all-deps.jar \
  --replace \
  "$1"
}

function java_fmt_recursive {
  for i in $(find . -name '*.java'); do java_fmt "$i"; done
}
```

What should I use instead to make the build happy?

**Comment by oscerd** [comment]
You should import the checkstyle file https://github.com/apache/camel-kafka-connector/blob/main/buildingtools/src/main/resources/camel-eclipse-checkstyle for example in Eclipse IDE and format the class.

**Comment by mathieux51** [comment]
Cool. I'll have a look at  Eclipse. 
_Notabene_: If there is any easy way to format with a CLI let me know 😇

**Comment by mathieux51** [comment]
@oscerd I tried to setup this [checkstyle](https://github.com/apache/camel-kafka-connector/blob/main/buildingtools/src/main/resources/camel-eclipse-checkstyle) and I wasn't very successful. I downloaded `eclipse-ide` and added this plugin https://checkstyle.org/eclipse-cs/#!/ but didn't find a way to make it work. How can I move forward? I'm still in the market for a CLI command that would return all linting errors

**Comment by oscerd** [comment]
I will try to merge this and fix the codestyle after merging.

**Comment by oscerd** [comment]
Thanks. I merged this one and fixed the CS.

**Comment by mathieux51** [comment]
Thank you @oscerd and sorry for the inconvenience

**Pull request closed without merging**
