### PR TITLE
Fix HDFS tests with Camel 3.4 (related to issue #263)

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
Strange error. It's unrelated to the change and I cannot reproduce it locally. Any ideas @oscerd ?

**Comment by oscerd** [comment]
I'm re-running the test. No idea really.

**Comment by oscerd** [comment]
Maybe we could remove the workaround

**Comment by orpiske** [comment]
> Maybe we could remove the workaround

+1. I logged an issue (#310) for this just in case we want to hold a bit on it.

**Comment by oscerd** [comment]
The containerlifecycle error seems to be related to the cometd version used aganist Jetty9

**Comment by orpiske** [comment]
> The containerlifecycle error seems to be related to the cometd version used aganist Jetty9

Great catch, thanks! I am on it.

**Comment by orpiske** [comment]
That did the trick, but I'll squash it so we have a clean history.

**Comment by oscerd** [comment]
Squashed and merged.

**Pull request merged**
