### PR TITLE
Auto gen step 2: generated connectors structure and dependencies.

### PR DESCRIPTION
**Pull request by valdar**

### CODE REVIEW

**Comment by orpiske** [comment]
This is looking great.

I think we could add `camel.sink.path.destinationName` and `camel.source.path.destinationName` to their respective configuration classes so that it easier to refer to them on the tests (and for documentation as well). 

What do you think @valdar ?

**Comment by valdar** [comment]
I don't fully get what you mean @orpiske :/

**Comment by orpiske** [comment]
> I don't fully get what you mean @orpiske :/

No worries. My comment was not very clear. I was thinking of about some connector specific configuration that we had. 

For example, I was thinking of this setting we used to set the [JMS destination address](https://github.com/apache/camel-kafka-connector/blob/master/connectors/camel-sjms2-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/sjms2/CamelSjms2SinkConnectorConfig.java#L152).   

I was just wondering/suggesting if it would OK to have those on the [CamelSinkConnectorConfig.java](https://github.com/apache/camel-kafka-connector/blob/master/core/src/main/java/org/apache/camel/kafkaconnector/CamelSinkConnectorConfig.java).

**Comment by valdar** [comment]
It should be already there https://github.com/apache/camel-kafka-connector/blob/master/connectors/camel-sjms2-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/sjms2/CamelSjms2SinkConnectorConfig.java#L152 or am I musunderstanding you again? :'(

**Comment by orpiske** [comment]
> It should be already there https://github.com/apache/camel-kafka-connector/blob/master/connectors/camel-sjms2-kafka-connector/src/main/java/org/apache/camel/kafkaconnector/sjms2/CamelSjms2SinkConnectorConfig.java#L152 or am I musunderstanding you again? :'(

You are correct. I did have a failure here because that was missing, but I guess it was some problem on my end.

**Pull request merged**
