### PR TITLE
Fix issue #159: camel components secret options are showed in logs

### PR DESCRIPTION
**Pull request by orpiske**
Beware: it also bumps camel dependency to ~3.7.1-SNAPSHOT~ 3.8.0-SNAPSHOT due to requiring apache/camel#4834

For 3.7.x, we'll depend on the backport pushed to apache/camel#4835.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Let's bump to 3.8 directly

**Comment by orpiske** [comment]
> Let's bump to 3.8 directly

Cool. I'll do that.

**Comment by oscerd** [comment]
For 3.7.1 it should be on 0.7.x branch

**Comment by orpiske** [comment]
> For 3.7.1 it should be on 0.7.x branch

Yeah, I know. I am preparing that one.

**Comment by oscerd** [comment]
Thanks

**Comment by oscerd** [comment]
> > For 3.7.1 it should be on 0.7.x branch
> 
> Yeah, I know. I am preparing that one.
> 
> I mean: I thought the camel-master was also pointed to 3.7.x for the time being, which why the PR was originally set to to 3.7.1-SNAPSHOT.

Yeah I forgot to point to 3.8.0

**Comment by oscerd** [comment]
Sorry

**Comment by orpiske** [comment]
> Sorry

No worries. After going through the process w/ 0.7.x I noticed it's a bit tricky and easy to miss stuff.

**Pull request merged**
