### PR TITLE
feat: add bulk upsert connector

### PR DESCRIPTION
**Pull request by Matheusafonsouza**

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Thanks, but you just need to add the kamelet to the kamelets repository and once we upgrade the version the connector will be automatically generated.

**Comment by Matheusafonsouza** [comment]
Thanks, i'll be doing It after make some tests on the connector

**Comment by valdar** [comment]
@Matheusafonsouza tnx for the contribution. Let me know if you need some help/guidance to contribute this in camel kamelets project.

**Comment by Matheusafonsouza** [comment]
@valdar i made some tests and the connector did not worked, i think that`s because i dont know much about the payload, no errors rised, just nothing

**Pull request closed without merging**
