### PR TITLE
Throttles strimzi startup to prevent resource reuse errors

### PR DESCRIPTION
**Pull request by orpiske**
This fixes some errors when launching the strimzi containers.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
Let's not merge this one yet. I found a failure in a test case not covered by Github Actions.

**Review by oscerd — APPROVED** [review]

**Review by valdar — APPROVED** [review]
:+1:

**Comment by orpiske** [comment]
So, it looks like the last set of changes fixed the issue. We should be good to go if passes on the checks.

**Comment by orpiske** [comment]
Looks good. Cleaning the tittle, labels and merging it.

**Pull request merged**
