### PR TITLE
Cut down the connectors number

### PR DESCRIPTION
**Pull request by oscerd**
referes to #279

### CODE REVIEW

**Comment by valdar** [comment]
I am not quite sure about removing `camel-kafka` ... isn't a legit usecase to read or send to _another_ Kafka cluster?

**Comment by oscerd** [comment]
You won't use kafka connect for something like that iko

**Comment by omarsmak** [comment]
For another kafka, that is a usecase for [MirrorMaker](https://kafka.apache.org/documentation/#basic_ops_mirror_maker) I think

**Comment by oscerd** [comment]
Yes, if you need to do something like that, you'd not use kafka-connect. There are other tools.

**Pull request merged**
