### PR TITLE
feat(docs): setup Antora

### PR DESCRIPTION
**Pull request by zregvart**
This sets up the Antora directory structure for the documentation and
adds a simple `index.adoc` as a starting point for the documentation.

### CODE REVIEW

**Comment by zregvart** [comment]
@oscerd I haven't included the xref link checker, like we have in Camel Quarkus:

https://github.com/apache/camel-quarkus/blob/e884ccbabeff2e8f50724be4e9ca5517a71723f4/docs/pom.xml#L115-L125

I can add that so when the project is built we don't have any broken links between the Asciidoc files.

**Comment by omarsmak** [comment]
That is awesome! Thank you @zregvart !

**Comment by oscerd** [comment]
@zregvart yeah, we can merge this one and adding the link checker in another PR

**Comment by zregvart** [comment]
I would like to polish the docs a bit. I'll have more PRs incoming.

**Pull request merged**
